CompileFlags: 
    Add: [-Wall, -Wpedantic, -std=c++17, -fsanitize=address, -fopenmp,
      -lhdf5_cpp, -lhdf5, -Weverythingo, -Wextra, -Wshadow, -Iinclude,  -I/usr/include/eigen3, -ferror-limit=0,
      ]
    CompilationDatabase: build/       # Search build/ directory for compile_commands.json


Diagnostics:
  ClangTidy:
    Add: [modernize*, bugprone-*, clang-analyzer*, cppcoreguidelines*, performance*,concurrency*,mpi*, openmp*,portability*, readability*, google-*,hicpp-* ]
    Remove: [modernize-use-trailing-return-type, cppcoreguidelines-avoid-magic-numbers, cppcoreguidelines-non-private-member-variables-in-classes,readability-identifier-naming,readability-magic-numbers,concurrency-mt-unsafe,google-runtime-int,readability-identifier-length,readability-function-cognitive-complexity]
  CheckOptions:
      readability-identifier-naming.VariableCase: CamelCase






